// <auto-generated />
namespace _01Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addSeverityrecords : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addSeverityrecords));
        
        string IMigrationMetadata.Id
        {
            get { return "201706201200077_add Severity records"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
